# -*- mode: ruby -*-
# vi: set ft=ruby  :

machines = {
  "wordpress" => {"memory" => "1024", "cpu" => "1", "clone" => "true", "ipA" => "250", "ipB" => "251", "image" => "ubuntu/jammy64"}
}

Vagrant.configure("2") do |config|
  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}"
      machine.vm.network "private_network", ip: "192.168.0.#{conf["ipA"]}"
      #machine.vm.network "public_network", ip: "172.16.0.#{conf["ipB"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        vb.linked_clone = conf["clone"]
      end
      machine.vm.synced_folder ".", "/vagrant", disabled: true
    end
  end
end
