---
- hosts: all
  tasks:
    - name: 'Instala pacotes de dependência'
      apt:
        name:
        - php
        - apache2
        - libapache2-mod-php
        - php-gd
        - libssh2-php
        - php-mcrypt
        - mysql-server-5.6
        - python-mysqldb
        - php-mysql
        state: latest
      become: yes