---
- name: "Baixa o arquivo do Wordpress"
  get_url:
    url: "https://wordpress.org/latest.tar.gz"
    dest: "/tmp/wordpress.tar.gz"

- name: "Descompacta o arquivo do Wordpress"
  unarchive:
    src: "/tmp/wordpress.tar.gz"
    dest: "/var/www/"
    remote_src: yes
  become: true

- name: "Criando o arquivo de configuração do Wordpress"
  copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: true

- name: "Configura o wp-config.php com as informações do banco de dados"
  replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: "database_name_here", value: "{{ wp_db_name }}" }
    - { regex: "username_here", value: "{{ wp_username }}" }
    - { regex: "password_here", value: "{{ wp_user_password }}" }
    - { regex: "localhost", value: "{{ wp_db_ip }}" }
  become: true

- name: "Configura o Apache para servir o Wordpress"
  template:
    src: "templates/000-default.conf.j2"
    dest: "/etc/apache2/sites-available/000-default.conf"
  become: true
  notify:
    - restart apache