---
- hosts: all
  tasks:
    - name: 'Instala pacotes de dependência'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - php
        - apache2
        - libapache2-mod-php