---
- hosts: all
  tasks:
    - name: 'Instala pacotes de dependência'
      apt:
        name:
        - php-common
        - apache2
        - libapache2-mod-php
        state: latest
      become: yes