---
- name: 'Instala pacotes do MySQL'
  apt:
    name:
      - mysql-server
      - python3-mysqldb
    state: latest
  #        update_cache: yes
  become: true

- name: "Cria o banco do MySQL"
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present
  become: true

- name: "Cria o usuário do MySQL"
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - "localhost"
    - "127.0.0.1"
    - "{{ wp_host_ip }}"
  become: true

- name: "Configura o MySQL para aceitar conexões remotas"
  copy:
    src: "files/mysqld.cnf"
    dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"
  become: true
  notify:
    - restart mysql
